// <auto-generated />
namespace ContosoUniversity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_dbo_Person_For_UploadImg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_dbo_Person_For_UploadImg));
        
        string IMigrationMetadata.Id
        {
            get { return "201902051511500_update_dbo_Person_For_UploadImg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
